language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO=2.2
  - DJANGO=3.1
  - DJANGO=3.2
  - DJANGO=main

matrix:
  fast_finish: true
  exclude:
    - python: "3.6"
      env: DJANGO=main
    - python: "3.7"
      env: DJANGO=main
  allow_failures:
    - env: DJANGO=main

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
