language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  fast_finish: true
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
    - python: "2.7"
      env: DJANGO=2.1
    - python: "2.7"
      env: DJANGO=master
    - python: "3.4"
      env: DJANGO=2.1
    - python: "3.4"
      env: DJANGO=master
  allow_failures:
    - env: DJANGO=master
    - python: "3.7-dev"

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
