# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-03-07 15:23

from django.db import migrations


def create_test_users(apps, schema_editor):
    User = apps.get_model('tests', 'User')
    for username, email, first_name, last_name, locale in [
        ('johnny', 'johnny@hotmail.com', 'John', 'Smith', 'en-us'),
        ('janek', 'janek@wp.pl', 'Jan', 'Kowalski', 'pl-pl'),
        ('giorgi', 'giorgi@iset.ge', 'გიორგი', 'ბერიძე', 'ka-ge'),
    ]:
        User.objects.create(
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
            locale=locale,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_create_user_type'),
    ]

    operations = [
        migrations.RunPython(
            create_test_users, reverse_code=migrations.RunPython.noop
        )
    ]
